# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d180f8c0ca372929c091e90deb80249e5b6fe68e8084692e0f5e0acfcc07ffd4681c3b649dedac5d42c0fec911973a4cf54db85d985df9aa612ea18f549f1b9c

test:
  secret_key_base: 078e07dfed4e71c3b2418c73bdf6388613c6be3f8e67ddf8627057fe2da527ccb6ed5d208c914fe575da89037b83a99c8ee7b9413d444168691bcd307c425558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
